"""
Typed schemas and Pydantic models for RecoverAI Agentic Recovery Planner & Orchestrator.
Adheres strictly to the principle: The LLM is an ADVISOR; the deterministic engine is the AUTHORITY.
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
from pydantic import BaseModel, Field, ConfigDict, field_validator, model_validator


class RecoveryAction(str, Enum):
    """Allowed recovery action space."""
    RETRY = "RETRY"
    PAYMENT_LINK = "PAYMENT_LINK"
    REMINDER = "REMINDER"
    WAIT = "WAIT"
    ESCALATE = "ESCALATE"
    STOP = "STOP"


class RecoveryPriority(str, Enum):
    """Priority tier for action dispatch."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FirewallDecision(str, Enum):
    """Verdict returned by the Recovery Firewall."""
    APPROVED = "APPROVED"
    STOP = "STOP"
    ESCALATE = "ESCALATE"


class AgentResultType(str, Enum):
    """Explicit result types for the orchestrator."""
    RECOVERY_SUCCESS = "RECOVERY_SUCCESS"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    SAFE_STOP = "SAFE_STOP"
    DO_NOT_RECOVER = "DO_NOT_RECOVER"
    INELIGIBLE_STATE = "INELIGIBLE_STATE"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    ESCALATED = "ESCALATED"
    CORRECTLY_WITHHELD = "CORRECTLY_WITHHELD"
    NO_ACTION = "NO_ACTION"
    MAX_RETRY_PROTECTION = "MAX_RETRY_PROTECTION"
    DUPLICATE_ACTION_BLOCKED = "DUPLICATE_ACTION_BLOCKED"
    RECOVERY_WAITING_ASYNC = "RECOVERY_WAITING_ASYNC"


class RecoveryContext(BaseModel):
    """
    Strongly typed, immutable context provided to the agent planner.
    Only VERIFIED_LOST payments may proceed to recovery planning.
    """
    model_config = ConfigDict(extra="allow", frozen=False)

    payment_id: str
    order_id: Optional[str] = None
    amount: float
    financial_state: str
    failure_code: Optional[str] = None
    failure_reason: Optional[str] = None
    failure_description: Optional[str] = None
    hardness: Optional[str] = None
    method: Optional[str] = None
    customer_segment: Optional[str] = None
    recovery_probability: Optional[float] = None
    expected_net_value: Optional[float] = None
    retry_count: int = 0
    previous_attempts: int = 1
    allowed_actions: List[str] = Field(default_factory=list)
    previous_actions: List[str] = Field(default_factory=list)

    @model_validator(mode="before")
    @classmethod
    def sync_failure_fields(cls, values: Any) -> Any:
        if isinstance(values, dict):
            fc = values.get("failure_code") or values.get("failure_reason")
            values["failure_code"] = fc
            values["failure_reason"] = fc
            if not values.get("failure_description") and fc:
                values["failure_description"] = f"Payment failure due to {fc}"
        return values


class AgentRecommendation(BaseModel):
    """
    Strongly typed recommendation generated by the Agentic Recovery Planner.
    Validated strictly before reaching the Recovery Firewall.
    """
    model_config = ConfigDict(extra="allow")

    action: RecoveryAction
    channel: Optional[str] = "gateway"
    timing: Optional[str] = "immediate"
    message_strategy: Optional[str] = None
    rationale: str = Field(default="", description="Detailed rationale for recommended strategy")
    reason: Optional[str] = None
    confidence: float = Field(default=0.85, ge=0.0, le=1.0)
    policy_references: List[str] = Field(default_factory=list)

    # Structured telemetry metadata (NO hidden chain-of-thought)
    observed_failure: Optional[str] = None
    selected_strategy: Optional[str] = None
    policy_basis: Optional[str] = None
    risk_level: Optional[str] = None

    # Priority & ENV compatibility
    priority: RecoveryPriority = RecoveryPriority.MEDIUM
    payment_id: Optional[str] = None
    expected_net_value: Optional[float] = None

    @model_validator(mode="before")
    @classmethod
    def sync_reason_and_rationale(cls, values: Any) -> Any:
        if isinstance(values, dict):
            r = values.get("rationale") or values.get("reason") or "Advisory agent recommendation."
            values["rationale"] = r
            values["reason"] = r
            if not values.get("selected_strategy") and values.get("action"):
                values["selected_strategy"] = str(values["action"])
        return values

    @field_validator("rationale")
    @classmethod
    def validate_rationale_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Rationale cannot be empty.")
        return v.strip()


# Backward compatibility alias
RecoveryPlan = AgentRecommendation


class FirewallResult(BaseModel):
    """
    Deterministic safety evaluation from the Recovery Firewall.
    """
    model_config = ConfigDict(extra="allow")

    status: FirewallDecision
    action: RecoveryAction
    rule_id: Optional[str] = None
    reason: str


class AgentExecutionResult(BaseModel):
    """
    Full closed-loop result of the agentic recovery lifecycle.
    """
    model_config = ConfigDict(extra="allow")

    payment_id: str
    order_id: Optional[str] = None
    financial_state: str
    failure_reason: Optional[str] = None
    amount: float
    recovery_probability: Optional[float] = None
    expected_net_value: Optional[float] = None

    agent_action: RecoveryAction
    agent_reason: str
    confidence: float = 1.0

    firewall_decision: FirewallDecision
    firewall_rule: Optional[str] = None
    firewall_reason: str

    execution_status: str = "NOT_EXECUTED"
    execution_detail: Optional[Dict[str, Any]] = None

    verification_state: Optional[str] = None
    final_result: str
    completed_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "payment_id": self.payment_id,
            "order_id": self.order_id,
            "financial_state": self.financial_state,
            "failure_reason": self.failure_reason,
            "amount": self.amount,
            "recovery_probability": self.recovery_probability,
            "expected_net_value": self.expected_net_value,
            "agent_action": self.agent_action.value if hasattr(self.agent_action, "value") else str(self.agent_action),
            "agent_reason": self.agent_reason,
            "confidence": self.confidence,
            "firewall_decision": self.firewall_decision.value if hasattr(self.firewall_decision, "value") else str(self.firewall_decision),
            "firewall_rule": self.firewall_rule,
            "firewall_reason": self.firewall_reason,
            "execution_status": self.execution_status,
            "execution_detail": self.execution_detail,
            "verification_state": self.verification_state,
            "final_result": self.final_result,
            "completed_at": self.completed_at,
        }
